name: Run Danger

on:
  pull_request:

jobs:
  danger:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install dependencies
        run: |
          bundle install

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger
