name: Unit tests

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Swift version
        run: |
            swift --version

      - name: Configure Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Execute tests
        run: |
          bundle exec fastlane run_tests
